name: Build unikernel and single application kernel images for all architectures and create manifests

on:
  workflow_call:
    inputs:
      app:
        description: "The target application to build"
        type: string
        required: true
      framework:
        description: "The target framework to build against"
        type: string
        required: true
      monitor:
        description: "The target monitor for the unikernel or single application kernel"
        type: string
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  build-image-amd64:
    name: Monitor ${{ inputs.monitor }}
    uses: ./.github/workflows/build_images.yml
    with:
      app: ${{ inputs.app }}
      framework: ${{ inputs.framework }}
      monitor: ${{ inputs.monitor }}
      runner: "ubuntu-22.04"
      arch: "amd64"

  build-image-arm64:
    name: Monitor ${{ inputs.monitor }}
    uses: ./.github/workflows/build_images.yml
    with:
      app: ${{ inputs.app }}
      framework: ${{ inputs.framework }}
      monitor: ${{ inputs.monitor }}
      runner: "ubuntu-22.04-arm"
      arch: "arm64"

  create-manifest:
    name: Create manifest of ${{ inputs.app }} over $${{ inputs.framework }} and ${{ inputs.monitor }}
    needs: [build-image-amd64,build-image-arm64]
    if: ${{ !cancelled() }}
    runs-on: ubuntu-22.04
    steps:

    ##- name: Install Cosign
    ##  uses: sigstore/cosign-installer@v3.4.0

    ##- name: Check install!
    ##  run: cosign version

    - name: Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}/hello-world-${{ inputs.monitor }}-${{ inputs.framework }}
        tags: |
          type=sha,prefix=,format=long

    - name: Create manifest
      run: |
        TAGS=${{ steps.meta.outputs.tags }}
        IMAGE=${{ env.REGISTRY }}/${{ github.repository }}/hello-world-${{ inputs.monitor }}-${{ inputs.framework }}
        docker manifest rm $TAGS || true
        if [[ "${{ needs.build-image-amd64.outputs.result }}" == "success" ]] &&
           [[ "${{ needs.build-image-arm64.outputs.result }}" == "success" ]]
        then
          docker manifest create $TAGS \
             --amend ${IMAGE}:amd64-${{ steps.meta.outputs.tag-names }} \
             --amend ${IMAGE}:arm64-${{ steps.meta.outputs.tag-names }}
        elif [[ "${{ needs.build-image-amd64.outputs.result }}" != "success" ]] &&
           [[ "${{ needs.build-image-arm64.outputs.result }}" == "success" ]]
        then
          docker manifest create $TAGS \
             --amend ${IMAGE}:arm64-${{ steps.meta.outputs.tag-names }}
        elif [[ "${{ needs.build-image-amd64.outputs.result }}" == "success" ]] &&
           [[ "${{ needs.build-image-arm64.outputs.result }}" != "success" ]]
        then
          docker manifest create $TAGS \
             --amend ${IMAGE}:amd64-${{ steps.meta.outputs.tag-names }}
        else
          echo "None of amd64 or arm64 images were built"
          exit 1
        fi
        HASH=$(docker manifest push $TAGS)
        echo "hash=$HASH" >> $GITHUB_ENV
        echo "tags=$TAGS" >> $GITHUB_ENV

    ##- name: Sign the published Docker image
    ##  env:
    ##    COSIGN_EXPERIMENTAL: "true"
    ##    DIGEST: ${{ env.hash }}
    ##    TAGS: ${{ env.tags }}
    ##  run: |
    ##    cosign sign --yes ${{ env.REGISTRY_IMAGE }}@${{ env.DIGEST }} \
    ##    -a "repo=${{github.repository}}" \
    ##    -a "workflow=${{github.workflow}}" \
    ##    -a "ref=${{github.sha}}" \
    ##    -a "author=urunc-dev/unikernel-build"
