name: Check and build changed apps

on:
  workflow_dispatch:
  push:
    branches:
      - ref_build_from_changed_files

jobs:
  get-changed-files:
    runs-on: ubuntu-22.04
    outputs:
      apps: ${{ steps.filter.outputs.changes }}
      changed_json: ${{ steps.format.outputs.build }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: filter
      uses: dorny/paths-filter@668c092af3649c4b664c54e4b704aa46782f6f7c
      with:
        list-files: 'json'
        token: ${{ secrets.GITHUB_TOKEN }}
        filters: |
          hello-world:
            - 'hello-world/**'
          hello-env:
            - 'hello-env/**'
          hello-exec-env:
            - 'hello-exec-env/**'
          hello-server:
            - 'hello-server/**'
          httpreply:
            - 'httpreply/**'
          nginx:
            - 'nginx/**'
          redis:
            - 'redis/**'
          net:
            - 'net/**'
          block-test:
            - 'block-test/**'
          whoami:
            - 'whoami/**'
          busybox:
            - 'busybox/**'

    - name: Format build json
      id: format
      run: |
        DIRS_TO_JSON=$(echo '${{ steps.filter.outputs.hello-world_files }}' | \
          jq -c 'reduce .[] as $path (
            {};
            ($path | split("/")) as $parts |
            ($parts[0:-1]) as $dirs |
            ($parts[-1]) as $file |
            
            reduce range(0; $dirs | length) as $i (
              .;
              setpath($dirs[0:$i+1]; getpath($dirs[0:$i+1]) // (if $i == (($dirs | length) - 1) then [] else {} end))
            ) |
            setpath($dirs; (getpath($dirs) + [$file]))
          )'
        )
        echo "build=$DIRS_TO_JSON" >> "$GITHUB_OUTPUT"

    - name: Show changed files
      run: |
        echo "Changes: ${{ steps.filter.outputs.changes }}"
        echo "Changed files in json: ${{ steps.format.outputs.build }}"

  for-each-app:
    name: Track changes for each app
    needs: get-changed-files
    strategy:
      fail-fast: false
      matrix:
        app: ${{ fromJSON(needs.get-changed-files.outputs.apps) }}
    uses: ./.github/workflows/separate_apps.yml
    with:
      app: ${{ matrix.app }}
      changed_apps: ${{ needs.get-changed-files.outputs.changed_json }}
