name: Build or Retrieve Linux Kernel

on:
  workflow_call:
    inputs:
      kernel_version:
        description: 'Linux Kernel version to build'
        required: true
        type: string
      defconfig_file:
        description: 'Path to defconfig JSON'
        required: true
        type: string
      registry:
        default: 'harbor.nbfc.io'
        required: false
        type: string
    secrets:
      GIT_CLONE_PAT:
        required: false
      harbor_user:
        required: false
      harbor_secret:
        required: false

  workflow_dispatch:
    inputs:
      kernel_version:
        description: 'Linux Kernel version to build'
        required: true
        type: string
      defconfig_file:
        description: 'Path to defconfig JSON'
        required: true
        type: string
      registry:
        default: 'harbor.nbfc.io'
        required: false
        type: string
    secrets:
      GIT_CLONE_PAT:
        required: false
      harbor_user:
        required: false
      harbor_secret:
        required: false
      
env:    
  REGISTRY: ${{ github.event.inputs.registry || 'harbor.nbfc.io' }}
  # NOTE: We assume that a project named after the repo owner exists in the
  # registry. The image will be uploaded as <repo_name> under the <repo_owner>
  # project.
  REGISTRY_IMAGE: ${{ github.repository }}
  RUNNER_ARCH_MAP: '[{"amd64":"x86_64", "arm64":"aarch64", "arm":"armv7l"}]'

jobs:
  check-artifact:
    runs-on: base-dind-2204-amd64
    steps:
      - uses: actions/checkout@v4

      - name: Load defconfig JSON
        id: defconfig
        run: |
          DEFCONFIG=$(jq -c . "${{ inputs.defconfig_file }}")
          echo "defconfig=$DEFCONFIG" >> $GITHUB_OUTPUT
      
      - name: Check if Kernel Artifact Exists
        id: check
        run: |
          echo "Checking for existing artifacts..."

          # Compute the hash of the defconfig contents
          CONFIG_HASH=$(echo -n "${{ steps.defconfig.outputs.defconfig }}" | md5sum | cut -d ' ' -f 1)
          echo "Config hash: $CONFIG_HASH"

          # Build the artifact name based on kernel_version and defconfig hash
          EXPECTED_ARTIFACT="linux-kernel-${{ inputs.kernel_version }}-${CONFIG_HASH}"
          echo "Expected artifact name: $EXPECTED_ARTIFACT"

          # List artifacts from previous successful runs of the 'Build Linux Kernel' workflow
          ARTIFACTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=completed&workflow=Build%20Linux%20Kernel" \
            | jq -r '.workflow_runs[].artifacts_url' | xargs -I {} curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            {} \
            | jq -r '.artifacts[].name')

          if echo "$ARTIFACTS" | grep -q "$EXPECTED_ARTIFACT"; then
            echo "Kernel artifact already exists! Skipping build."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No matching artifact found. Proceeding with build."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if Kernel Artifact Exists
        id: check-fc
        run: |
          echo "Checking for existing artifacts..."

          # Compute the hash of the defconfig contents
          CONFIG_HASH=$(echo -n "${{ steps.defconfig.outputs.defconfig }}" | md5sum | cut -d ' ' -f 1)
          echo "Config hash: $CONFIG_HASH"

          # Build the artifact name based on kernel_version and defconfig hash
          EXPECTED_ARTIFACT="linux-kernel-fc-${{ inputs.kernel_version }}-${CONFIG_HASH}"
          echo "Expected artifact name: $EXPECTED_ARTIFACT"

          # List artifacts from previous successful runs of the 'Build Linux Kernel' workflow
          ARTIFACTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?status=completed&workflow=Build%20Linux%20Kernel" \
            | jq -r '.workflow_runs[].artifacts_url' | xargs -I {} curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            {} \
            | jq -r '.artifacts[].name')

          if echo "$ARTIFACTS" | grep -q "$EXPECTED_ARTIFACT"; then
            echo "Kernel artifact already exists! Skipping build."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "No matching artifact found. Proceeding with build."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build Linux Kernel
        if: ${{ steps.check.outputs.exists == 'false' || steps.check-fc.outputs.exists == 'false' }}
        run: |
          git clone --depth 1 --branch v${{ inputs.kernel_version }} https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git linux-source
          cd linux-source
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison libssl-dev libelf-dev bc
          echo "${{ inputs.defconfig }}" > .config
          make olddefconfig
          make -j$(nproc)
          CONFIG_HASH=$(echo -n "${{ steps.defconfig.outputs.defconfig }}" | md5sum | cut -d ' ' -f 1)
          echo "config_hash=${CONFIG_HASH}" >> $GITHUB_ENV

      - name: Archive Kernel Artifact
        if: ${{ steps.check.outputs.exists == 'false' || steps.check-fc.outputs.exists == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-${{ inputs.kernel_version }}-${{ env.config_hash }}
          path: linux-source/arch/x86/boot/bzImage

      - name: Archive Kernel Artifact FC
        if: ${{ steps.check.outputs.exists == 'false' || steps.check-fc.outputs.exists == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: linux-kernel-fc-${{ inputs.kernel_version }}-${{ env.config_hash }}
          path: linux-source/vmlinux
