name: OCI image push

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  build-rumprun:
    strategy:
      matrix:
        unikernel: [ rumprun-httpreply ]
        hypervisor: [ hvt, spt ]
      fail-fast: false
    uses: ./.github/workflows/build-bunny.yml
    with:
      unikernel: ${{ matrix.unikernel }}
      hypervisor: ${{ matrix.hypervisor }}
    secrets: inherit

  manifest-rumprun:
    needs: [build-rumprun]
    uses: ./.github/workflows/manifest.yml
    strategy:
      matrix:
        unikernel: [ rumprun-httpreply ]
        hypervisor: [ hvt, spt ]
    with:
      unikernel: ${{ matrix.unikernel }}
      hypervisor: ${{ matrix.hypervisor }}
    secrets: inherit

  build-unikraft:
    strategy:
      matrix:
        unikernel: [ nginx ]
        hypervisor: [ fc, qemu]
      fail-fast: false
    uses: ./.github/workflows/build-bunny.yml
    with:
      unikernel: ${{ matrix.unikernel }}
      hypervisor: ${{ matrix.hypervisor }}
    secrets: inherit

  manifest-unikraft:
    needs: [build-unikraft]
    uses: ./.github/workflows/manifest.yml
    strategy:
      matrix:
        unikernel: [ nginx ]
        hypervisor: [ fc, qemu ]
    with:
      unikernel: ${{ matrix.unikernel }}
      hypervisor: ${{ matrix.hypervisor }}
    secrets: inherit

  # build-unikraft-local:
  #   strategy:
  #     matrix:
  #       archconfig: [ amd64, arm64 ]
  #       unikernel: [ httpreply ]
  #       hypervisor: [ qemu, fc]
  #     fail-fast: false
  #   uses: ./.github/workflows/build-unikraft-local.yml
  #   with:
  #     matrix: ${{ matrix.archconfig }}
  #     unikernel: ${{ matrix.unikernel }}
  #     hypervisor: ${{ matrix.hypervisor }}
  #   secrets: inherit 
  #     # aws_access_key: ${{ secrets.AWS_ACCESS_KEY}}
  #     # aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
  #     # harbor_user: ${{ secrets.HARBOR_USER }}
  #     # harbor_secret: ${{ secrets.HARBOR_SECRET }}

  # manifest-unikraft-local:
  #   needs: [build-unikraft-local]
  #   uses: ./.github/workflows/manifest.yml
  #   strategy:
  #     matrix:
  #       archconfig: [ amd64, arm64 ]
  #       unikernel: [ httpreply ]
  #       hypervisor: [ qemu, fc]
  #   with:
  #     # matrix: ${{ matrix.archconfig }}
  #     unikernel: ${{ matrix.unikernel }}
  #     hypervisor: ${{ matrix.hypervisor }}
  #   secrets: inherit

  # build-chttp-unikraft:
  #   strategy:
  #     matrix:
  #       unikernel: [ chttp-unikraft ]
  #       hypervisor: [ qemu ]
  #     fail-fast: false
  #   uses: ./.github/workflows/build-bunny.yml
  #   with:
  #     unikernel: ${{ matrix.unikernel }}
  #     hypervisor: ${{ matrix.hypervisor }}
  #   secrets: inherit

  # manifest-chttp-unikraft:
  #   needs: [build-chttp-unikraft]
  #   uses: ./.github/workflows/manifest.yml
  #   strategy:
  #     matrix:
  #       unikernel: [ chttp-unikraft ]
  #       hypervisor: [ qemu ]
  #   with:
  #     unikernel: ${{ matrix.unikernel }}
  #     hypervisor: ${{ matrix.hypervisor }}
  #   secrets: inherit

  build-linux-kernel:
    strategy:
      fail-fast: false
    uses: ./.github/workflows/build-kernel.yml
    with:
      kernel_version: "6.14"
      # unikernel: ${{ matrix.unikernel }}
      # hypervisor: ${{ matrix.hypervisor }}
      defconfig_file: "configs/defconfig.json"
    secrets: inherit

  build-linux-unikernels:
    needs: build-linux-kernel
    strategy:
      matrix:
        unikernel: [ nginx, redis ]
        hypervisor: [ qemu, fc ]
      fail-fast: false
    uses: ./.github/workflows/build-linux-unikernel.yml
    with:
      kernel_version: "6.14"
      unikernel: ${{ matrix.unikernel }}
      hypervisor: ${{ matrix.hypervisor }}
      defconfig_file: "configs/defconfig.json"
    secrets: inherit